// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA5oq9ht6JtC96Y7PGRGfgAVmhYNa27s5A',
    appId: '1:439131287397:web:0ceeacaff5a07d247dbb8c',
    messagingSenderId: '439131287397',
    projectId: 'viaauth',
    authDomain: 'viaauth.firebaseapp.com',
    storageBucket: 'viaauth.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCkgwKUn1_sGpiMuIiXfPAIe9YvUx0coog',
    appId: '1:439131287397:android:e44efdb5029f37db7dbb8c',
    messagingSenderId: '439131287397',
    projectId: 'viaauth',
    storageBucket: 'viaauth.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCLczfyMP92u2kmyUw6phAb6kIEFe2iYa0',
    appId: '1:439131287397:ios:0a9f470ebe18824d7dbb8c',
    messagingSenderId: '439131287397',
    projectId: 'viaauth',
    storageBucket: 'viaauth.firebasestorage.app',
    iosBundleId: 'com.viaveri.vialearn',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCLczfyMP92u2kmyUw6phAb6kIEFe2iYa0',
    appId: '1:439131287397:ios:b6e540c2862322d87dbb8c',
    messagingSenderId: '439131287397',
    projectId: 'viaauth',
    storageBucket: 'viaauth.firebasestorage.app',
    iosBundleId: 'com.example.vialearnFlutter',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA5oq9ht6JtC96Y7PGRGfgAVmhYNa27s5A',
    appId: '1:439131287397:web:9ef7594a4b6e5b0f7dbb8c',
    messagingSenderId: '439131287397',
    projectId: 'viaauth',
    authDomain: 'viaauth.firebaseapp.com',
    storageBucket: 'viaauth.firebasestorage.app',
  );

}